### PR TITLE
Geometry

### PR DESCRIPTION
**Pull request by lorenzoesposito2**
Creating a new branch for the implementation of geometry functionalities.

### CODE REVIEW

**Comment by lorenzoesposito2** [comment]
Hi Giovanni! I finished developing the Point class, now the transformation class is missing, i start working on it

**Comment by GiovanniPellegrini** [comment]
Hi Lorenzo. Today I can work on transformation tests. Tell me if it is ok to you

**Comment by lorenzoesposito2** [comment]
Ok Giovanni now all that remains is to develop the tests for the transformation class, here is the list of tests to be implemented

- [x] Test isClose()
- [x] Test Multiplication()
- [x] Test Vec/Point/Normalmultiplication()
- [x] Test inverse()
- [x] Test translation()

**Comment by GiovanniPellegrini** [comment]
> Ok Giovanni now all that remains is to develop the tests for the transformation class, here is the list of tests to be implemented
> 
> * [ ]  Test isClose()
> * [ ]  Test Multiplication()
> * [ ]  Test Vec/Point/Normalmultiplication()
> * [ ]  Test inverse()
> * [ ]  Test translation()

**Comment by GiovanniPellegrini** [comment]
Thanks Lorenzo, your to-do list is very helpful

**Comment by GiovanniPellegrini** [comment]
Now all the test should work. Hope you'll undesterstand my tests. 
Xoxo

**Pull request merged**
