### PR TITLE
camera

### PR DESCRIPTION
**Pull request by lorenzoesposito2**
In this branch we are going to develop camera and ray classes

### CODE REVIEW

**Comment by lorenzoesposito2** [comment]
Hi Giovanni! i finished to develop the Class ImageTracer i have also made the tests. if i'm not mistaken we just need to conclude the development of the Class camera and its derivatives, then we can merge the branch!

**Comment by GiovanniPellegrini** [comment]
Hi Lorenzo. Ye, our work is almost done.

Here a task list to help me (and maybe you)

- [x] test for moving observer (in OrthogonalCamera tests)
- [x] test for PerspectiveCamera: depart from the same point
- [x]  test for PerspectiveCamera: hitting right points

**Comment by lorenzoesposito2** [comment]
hi Giovanni!
I have developed the tests for perspectiveCamera and the transformation test for orthogonalCamera (i don't know if it corresponds to the first test in the to do list). 
When you can could you also check if we are missing something to implement?

P.S I'm not very good at writing function docstrings so if you want to improve them a bit I'm glad.
thanks

**Comment by lorenzoesposito2** [comment]
Hi Gio! 
I checked the code and it seems to me that nothing is missing if you agree we can merge the pull request
siuuu

**Pull request merged**
