### PR TITLE
Fix issue #9

### PR DESCRIPTION
**Pull request by GiovanniPellegrini**
PR regarding bug #9 . There is a issue in transformation*Normal classes

### CODE REVIEW

**Comment by GiovanniPellegrini** [comment]
Hi Lorenzo, now the bug should be fixed. I'll do some other tests just to be sure. 

While I'm at it, I'll remind you that today is George Lucas' birthday. May the force be with you
tumblr_oad60zmf5I1qh7on9o1_500

**Comment by lorenzoesposito2** [comment]
thanks Giovanni, then I will also try to do a check to see if this bug was backfiring in other features of the code
star-wars-funny-icegif-8

**Comment by lorenzoesposito2** [comment]
hi Giovanni, if you find the bug please make a commit where the tests fail with a brief explanation so I understand where the bug was

**Comment by GiovanniPellegrini** [comment]
Hi Lorenzo, the previous commits failed the tests because there was a problem in the plane classes. Now everything is fixed

**Pull request merged**
