### PR TITLE
Demo 

### PR DESCRIPTION
**Pull request by GiovanniPellegrini**
We want to add Sphere to create our black triangle

### CODE REVIEW

**Comment by GiovanniPellegrini** [comment]
Here a to do list 

- [x] Shape
   -  [x] rayIntersaction function
  

- [x] Hit record
    - [x] Parameters
    - [x] Test

- [x] Sphere
    - [x] Normal 
    - [x] Point to u_v
    - [x] HitRecord
    - [x] Tests

- [ ] World
     - [x] RayIntersaction iteration above all shapes
     - [ ]   Create the scene with 10 sphere

- [ ] Actions

**Comment by lorenzoesposito2** [comment]
Hi Giovanni! I was looking on the web at possible interfaces for our Tracer Kotlin. 
I propose
CLIKT: [https://ajalt.github.io/clikt/](url) which is widely used and easy to use

**Comment by GiovanniPellegrini** [comment]
Dear Lorenzo,
unfortunately I can find anything to the link that you sent to me. I'm very sorry, could you send it again? 

Xoxo

**Comment by lorenzoesposito2** [comment]
sorry this is the right link

[https://ajalt.github.io/clikt/](url)

**Comment by lorenzoesposito2** [comment]
Hi Giovanni! i will do a commit with demo adding .sh file to make animation and all the other stuff updated like the Main file.
Then if you agree i'll merge this pull request

**Comment by lorenzoesposito2** [comment]
We've done a lot of things now it's time to merge
1*_qX0u7Xn8cyT3pAYh_6eRw

**Pull request merged**
